openapi: 3.0.0
info:
  title: MTG Price Bot
  version: 1.0.0
servers:
- url: https://d5dv3vf1vap43u1ntal1.apigw.yandexcloud.net
paths:
  /vk:
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbas46c2ost7vshid40k
        service_account_id: ajeomjp59v0jb9uiiq3k
  /tg:
    post:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: bbas46c2ost7vshid40k
        service_account_id: ajeomjp59v0jb9uiiq3k
